/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package posture_analysis;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author nhaza
 */
public class PhotoFrame extends javax.swing.JFrame {
    int yuklenenFotoSayisi = 0;
    String yandanYol = "";
    String karsidanYol = "";

    /**
     * Creates new form PhotoFrame
     */
    public PhotoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_yandan = new javax.swing.JLabel();
        jLabel_karsidan = new javax.swing.JLabel();
        jButton_yandan = new javax.swing.JButton();
        jButton_karsidan = new javax.swing.JButton();
        jLabel_sonuc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_geri = new javax.swing.JButton();
        jButton_ileri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 25, 47));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(612, 50));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("MingLiU-ExtB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 255, 218));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\photographer.png")); // NOI18N
        jLabel1.setText("FOTOGRAF EKLEME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 0, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ayakta çekilmiş 2 fotoğrafınızı ekleyin.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 11, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel_yandan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_yandan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_yandan.setText("YANDAN GÖRÜNÜM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 79, 0, 0);
        jPanel1.add(jLabel_yandan, gridBagConstraints);

        jLabel_karsidan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_karsidan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_karsidan.setText("KARŞIDAN GÖRÜNÜM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 204, 0, 0);
        jPanel1.add(jLabel_karsidan, gridBagConstraints);

        jButton_yandan.setBackground(new java.awt.Color(204, 214, 246));
        jButton_yandan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_yandan.setText("FOTOĞRAF YÜKLE");
        jButton_yandan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_yandanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 79, 0, 0);
        jPanel1.add(jButton_yandan, gridBagConstraints);

        jButton_karsidan.setBackground(new java.awt.Color(204, 214, 246));
        jButton_karsidan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_karsidan.setText("FOTOĞRAF YÜKLE");
        jButton_karsidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_karsidanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 204, 0, 0);
        jPanel1.add(jButton_karsidan, gridBagConstraints);

        jLabel_sonuc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_sonuc.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_sonuc.setText("2 adet fotoğraf bekleniyor...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 21, 0, 0);
        jPanel1.add(jLabel_sonuc, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(10, 25, 47));

        jButton_geri.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\turn-left (1).png")); // NOI18N
        jButton_geri.setText("GERİ");
        jButton_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_geriActionPerformed(evt);
            }
        });

        jButton_ileri.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_ileri.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\icons8-forward-50.png")); // NOI18N
        jButton_ileri.setText("İLERİ");
        jButton_ileri.setEnabled(false);
        jButton_ileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ileriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_geri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, Short.MAX_VALUE)
                .addComponent(jButton_ileri)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_geri)
                    .addComponent(jButton_ileri, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 520;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(187, 6, 6, 5);
        jPanel1.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_yandanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_yandanActionPerformed
        // TODO add your handling code here:
            fotoEkle(jLabel_yandan,"yandan");
            fotoDurumunuGuncelle();
    }//GEN-LAST:event_jButton_yandanActionPerformed

    private void jButton_karsidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_karsidanActionPerformed
       fotoEkle(jLabel_karsidan,"karsidan");
       fotoDurumunuGuncelle();
    }//GEN-LAST:event_jButton_karsidanActionPerformed

    private void jButton_ileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ileriActionPerformed
       try {
        String tamYol = "C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\rehber.png";
        
        java.io.File dosya = new java.io.File(tamYol);
        
        if (dosya.exists()) {
            ImageIcon icon = new ImageIcon(dosya.getAbsolutePath());
            // Senin istediğin 600x435 boyutuna getiriyoruz
            Image img = icon.getImage().getScaledInstance(600, 435, Image.SCALE_SMOOTH);
            
            JLabel lbl = new JLabel(new ImageIcon(img));
            JOptionPane.showMessageDialog(this, lbl, "Analiz Rehberi", JOptionPane.PLAIN_MESSAGE);
            
            
        } else {
            
            System.out.println("Dosya fiziksel olarak yok: " + tamYol);
            JOptionPane.showMessageDialog(this, "Rehber fotoğrafı belirtilen adreste bulunamadı!");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
        YandanAnalizFrame yandanAnaliz = new YandanAnalizFrame(this.yandanYol, this.karsidanYol);
        yandanAnaliz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_ileriActionPerformed

    private void jButton_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_geriActionPerformed
        // TODO add your handling code here:
        KullaniciBilgiFrame kullaniciBilgi = new KullaniciBilgiFrame();
        kullaniciBilgi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_geriActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhotoFrame().setVisible(true);
            }
        });
    }
       private void fotoDurumunuGuncelle() {
           int kalan = 2;
        if (!yandanYol.isEmpty() && !karsidanYol.isEmpty() ) {
            jLabel_sonuc.setText("Fotoğrafları başarılı bir şekilde yüklediniz.");
            jLabel_sonuc.setForeground(new java.awt.Color(0, 153, 0));
            
        }else if (!karsidanYol.isEmpty() || !yandanYol.isEmpty()) {
            jLabel_sonuc.setText("1 adet fotoğraf bekleniyor...");
        }else{
            jLabel_sonuc.setText("2 adet fotoğraf bekleniyor...");
        }
    }

    private void fotoEkle(javax.swing.JLabel labelKutusu,String tip) {
        JFileChooser fileChooser = new JFileChooser();
        int sonuc = fileChooser.showOpenDialog(this);

        if (sonuc == JFileChooser.APPROVE_OPTION) {
            String yol = fileChooser.getSelectedFile().getAbsolutePath();
        
            if (tip.equals("yandan")) {
                yandanYol = yol; 
            } else if (tip.equals("karsidan")) {
                karsidanYol = yol;
            }
            java.io.File secilenDosya = fileChooser.getSelectedFile();
            ImageIcon tikIcon = new ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\tick.png"); 
            Image img = tikIcon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        
            labelKutusu.setIcon(new ImageIcon(img));
            labelKutusu.setText("Fotoğraf Yüklendi!");
            labelKutusu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            labelKutusu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            
            if (!yandanYol.isEmpty() && !karsidanYol.isEmpty()) {
            jButton_ileri.setEnabled(true);
            }
        // Bu iki satırı IF bloğunun dışına, metodun en sonuna al ki her yüklemede çalışsın:
        yuklenenFotoSayisi++;
        fotoDurumunuGuncelle();
               }

           }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_geri;
    private javax.swing.JButton jButton_ileri;
    private javax.swing.JButton jButton_karsidan;
    private javax.swing.JButton jButton_yandan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_karsidan;
    private javax.swing.JLabel jLabel_sonuc;
    private javax.swing.JLabel jLabel_yandan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
