/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package posture_analysis;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author nhaza
 */
public class PhotoFrame extends javax.swing.JFrame {
    int yuklenenFotoSayisi = 0;
    String yandanYol = "";
    String karsidanYol = "";

    /**
     * Creates new form PhotoFrame
     */
    public PhotoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_yandan = new javax.swing.JLabel();
        jLabel_karsidan = new javax.swing.JLabel();
        jButton_yandan = new javax.swing.JButton();
        jButton_karsidan = new javax.swing.JButton();
        jLabel_sonuc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_geri = new javax.swing.JButton();
        jButton_ileri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 25, 47));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(612, 50));

        jLabel1.setFont(new java.awt.Font("MingLiU-ExtB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 255, 218));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\photographer.png")); // NOI18N
        jLabel1.setText("FOTOGRAF EKLEME");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ayakta çekilmiş 2 fotoğrafınızı ekleyin.");

        jLabel_yandan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_yandan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_yandan.setText("YANDAN GÖRÜNÜM");

        jLabel_karsidan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_karsidan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_karsidan.setText("KARŞIDAN GÖRÜNÜM");

        jButton_yandan.setBackground(new java.awt.Color(204, 214, 246));
        jButton_yandan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_yandan.setText("FOTOĞRAF YÜKLE");
        jButton_yandan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_yandanActionPerformed(evt);
            }
        });

        jButton_karsidan.setBackground(new java.awt.Color(204, 214, 246));
        jButton_karsidan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_karsidan.setText("FOTOĞRAF YÜKLE");
        jButton_karsidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_karsidanActionPerformed(evt);
            }
        });

        jLabel_sonuc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_sonuc.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_sonuc.setText("2 adet fotoğraf bekleniyor...");

        jPanel2.setBackground(new java.awt.Color(10, 25, 47));

        jButton_geri.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\turn-left (1).png")); // NOI18N
        jButton_geri.setText("GERİ");
        jButton_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_geriActionPerformed(evt);
            }
        });

        jButton_ileri.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_ileri.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\icons8-forward-50.png")); // NOI18N
        jButton_ileri.setText("İLERİ");
        jButton_ileri.setEnabled(false);
        jButton_ileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ileriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_geri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(jButton_ileri)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton_geri))
                    .addComponent(jButton_ileri, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_yandan)
                    .addComponent(jButton_yandan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_karsidan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_karsidan, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_sonuc)
                        .addGap(228, 228, 228))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_karsidan)
                    .addComponent(jLabel_yandan))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton_karsidan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton_yandan)))
                .addGap(28, 28, 28)
                .addComponent(jLabel_sonuc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_yandanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_yandanActionPerformed
        // TODO add your handling code here:
            fotoEkle(jLabel_yandan,"yandan");
            fotoDurumunuGuncelle();
    }//GEN-LAST:event_jButton_yandanActionPerformed

    private void jButton_karsidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_karsidanActionPerformed
       fotoEkle(jLabel_karsidan,"karsidan");
       fotoDurumunuGuncelle();
    }//GEN-LAST:event_jButton_karsidanActionPerformed

    private void jButton_ileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ileriActionPerformed
       try {
        String tamYol = "C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\rehber.png";
        
        java.io.File dosya = new java.io.File(tamYol);
        
        if (dosya.exists()) {
            ImageIcon icon = new ImageIcon(dosya.getAbsolutePath());
            // Senin istediğin 600x435 boyutuna getiriyoruz
            Image img = icon.getImage().getScaledInstance(600, 435, Image.SCALE_SMOOTH);
            
            JLabel lbl = new JLabel(new ImageIcon(img));
            JOptionPane.showMessageDialog(this, lbl, "Analiz Rehberi", JOptionPane.PLAIN_MESSAGE);
            
            
        } else {
            
            System.out.println("Dosya fiziksel olarak yok: " + tamYol);
            JOptionPane.showMessageDialog(this, "Rehber fotoğrafı belirtilen adreste bulunamadı!");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
       YandanAnalizFrame yandanAnaliz = new YandanAnalizFrame(yandanYol);
       yandanAnaliz.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton_ileriActionPerformed

    private void jButton_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_geriActionPerformed
        // TODO add your handling code here:
        KullaniciBilgiFrame kullaniciBilgi = new KullaniciBilgiFrame();
        kullaniciBilgi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_geriActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhotoFrame().setVisible(true);
            }
        });
    }
       private void fotoDurumunuGuncelle() {
           int kalan = 2;
        if (!yandanYol.isEmpty() && !karsidanYol.isEmpty() ) {
            jLabel_sonuc.setText("Fotoğrafları başarılı bir şekilde yüklediniz.");
            jLabel_sonuc.setForeground(new java.awt.Color(0, 153, 0));
            
        }else if (!karsidanYol.isEmpty() || !yandanYol.isEmpty()) {
            jLabel_sonuc.setText("1 adet fotoğraf bekleniyor...");
        }else{
            jLabel_sonuc.setText("2 adet fotoğraf bekleniyor...");
        }
    }

    private void fotoEkle(javax.swing.JLabel labelKutusu,String tip) {
        JFileChooser fileChooser = new JFileChooser();
        int sonuc = fileChooser.showOpenDialog(this);

        if (sonuc == JFileChooser.APPROVE_OPTION) {
            String yol = fileChooser.getSelectedFile().getAbsolutePath();
        
            if (tip.equals("yandan")) {
                yandanYol = yol; 
            } else if (tip.equals("karsidan")) {
                karsidanYol = yol;
            }
            java.io.File secilenDosya = fileChooser.getSelectedFile();
            ImageIcon tikIcon = new ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\tick.png"); 
            Image img = tikIcon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        
            labelKutusu.setIcon(new ImageIcon(img));
            labelKutusu.setText("Fotoğraf Yüklendi!");
            labelKutusu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            labelKutusu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            
            if (!yandanYol.isEmpty() && !karsidanYol.isEmpty()) {
                jButton_ileri.setEnabled(true);
        
        yuklenenFotoSayisi++;
        fotoDurumunuGuncelle();
        }
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_geri;
    private javax.swing.JButton jButton_ileri;
    private javax.swing.JButton jButton_karsidan;
    private javax.swing.JButton jButton_yandan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_karsidan;
    private javax.swing.JLabel jLabel_sonuc;
    private javax.swing.JLabel jLabel_yandan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
