
package posture_analysis;

import java.awt.Point;
import java.util.List;


public class SonucFrame extends javax.swing.JFrame {
    private List<Point> yanNoktalar;
    private List<Point> onNoktalar;
    private String yanYol;   // Geri dönüş için saklıyoruz
    private String onYol;    // Geri dönüş için saklıyoruz
    private List<AnalizSonucu> tumSonuclar = new java.util.ArrayList<>();
    
    public SonucFrame() {
        initComponents();
    }
    public SonucFrame(List<Point> yan, List<Point> on, String yanYolu, String onYolu) {
        this.yanNoktalar = yan;
        this.onNoktalar = on;
        this.yanYol = yanYolu;
        this.onYol = onYolu;
        
        initComponents();
        analizVeGoster();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_diz = new javax.swing.JPanel();
        jLabel_diz_puan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel_omuz = new javax.swing.JPanel();
        jLabel_omuz_puan = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel_bas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_bas_puan = new javax.swing.JLabel();
        jPanel_sirt = new javax.swing.JPanel();
        jLabel_sirt_puan = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel_bel = new javax.swing.JPanel();
        jLabel_bel_puan = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel_pelvis = new javax.swing.JPanel();
        jLabel_pelvis_puan = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton_ileri = new javax.swing.JButton();
        jButton_geri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 25, 47));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_diz.setBackground(new java.awt.Color(17, 34, 64));
        jPanel_diz.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 255, 218), 2, true));

        jLabel_diz_puan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_diz_puan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_diz_puan.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\marking.png")); // NOI18N
        jLabel_diz_puan.setText("Puanınız : ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\x-ray.png")); // NOI18N
        jLabel12.setText("DİZLER");

        javax.swing.GroupLayout jPanel_dizLayout = new javax.swing.GroupLayout(jPanel_diz);
        jPanel_diz.setLayout(jPanel_dizLayout);
        jPanel_dizLayout.setHorizontalGroup(
            jPanel_dizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_dizLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(79, 79, 79))
            .addGroup(jPanel_dizLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel_diz_puan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_dizLayout.setVerticalGroup(
            jPanel_dizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_dizLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addGap(30, 30, 30)
                .addComponent(jLabel_diz_puan)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_diz, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 270, 220));

        jPanel_omuz.setBackground(new java.awt.Color(17, 34, 64));
        jPanel_omuz.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 255, 218), 2, true));

        jLabel_omuz_puan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_omuz_puan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_omuz_puan.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\marking.png")); // NOI18N
        jLabel_omuz_puan.setText("Puanınız : ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\shoulder.png")); // NOI18N
        jLabel9.setText("OMUZLAR");

        javax.swing.GroupLayout jPanel_omuzLayout = new javax.swing.GroupLayout(jPanel_omuz);
        jPanel_omuz.setLayout(jPanel_omuzLayout);
        jPanel_omuzLayout.setHorizontalGroup(
            jPanel_omuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_omuzLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel_omuz_puan)
                .addGap(52, 52, 52))
            .addGroup(jPanel_omuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_omuzLayout.createSequentialGroup()
                    .addContainerGap(67, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(42, 42, 42)))
        );
        jPanel_omuzLayout.setVerticalGroup(
            jPanel_omuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_omuzLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel_omuz_puan)
                .addGap(25, 25, 25))
            .addGroup(jPanel_omuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_omuzLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel9)
                    .addContainerGap(117, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel_omuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 270, 220));

        jPanel_bas.setBackground(new java.awt.Color(17, 34, 64));
        jPanel_bas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 255, 218), 2, true));
        jPanel_bas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_basMouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\kafa.png")); // NOI18N
        jLabel1.setText("BAŞ VE BOYUN");

        jLabel_bas_puan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_bas_puan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_bas_puan.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\marking.png")); // NOI18N
        jLabel_bas_puan.setText("Puanınız : ");

        javax.swing.GroupLayout jPanel_basLayout = new javax.swing.GroupLayout(jPanel_bas);
        jPanel_bas.setLayout(jPanel_basLayout);
        jPanel_basLayout.setHorizontalGroup(
            jPanel_basLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_basLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel_basLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_bas_puan)
                    .addComponent(jLabel1))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel_basLayout.setVerticalGroup(
            jPanel_basLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_basLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel_bas_puan)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 220));

        jPanel_sirt.setBackground(new java.awt.Color(17, 34, 64));
        jPanel_sirt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 255, 218), 2, true));

        jLabel_sirt_puan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_sirt_puan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_sirt_puan.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\marking.png")); // NOI18N
        jLabel_sirt_puan.setText("Puanınız : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\dromedary.png")); // NOI18N
        jLabel8.setText("SIRT");

        javax.swing.GroupLayout jPanel_sirtLayout = new javax.swing.GroupLayout(jPanel_sirt);
        jPanel_sirt.setLayout(jPanel_sirtLayout);
        jPanel_sirtLayout.setHorizontalGroup(
            jPanel_sirtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sirtLayout.createSequentialGroup()
                .addGroup(jPanel_sirtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_sirtLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel8))
                    .addGroup(jPanel_sirtLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel_sirt_puan)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel_sirtLayout.setVerticalGroup(
            jPanel_sirtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_sirtLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addComponent(jLabel_sirt_puan)
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel_sirt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 270, 220));

        jPanel_bel.setBackground(new java.awt.Color(17, 34, 64));
        jPanel_bel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 255, 218), 2, true));

        jLabel_bel_puan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_bel_puan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_bel_puan.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\marking.png")); // NOI18N
        jLabel_bel_puan.setText("Puanınız : ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\back-pain.png")); // NOI18N
        jLabel10.setText("BEL");

        javax.swing.GroupLayout jPanel_belLayout = new javax.swing.GroupLayout(jPanel_bel);
        jPanel_bel.setLayout(jPanel_belLayout);
        jPanel_belLayout.setHorizontalGroup(
            jPanel_belLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_belLayout.createSequentialGroup()
                .addGroup(jPanel_belLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_belLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel_bel_puan))
                    .addGroup(jPanel_belLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel10)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel_belLayout.setVerticalGroup(
            jPanel_belLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_belLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel_bel_puan)
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel_bel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 270, 220));

        jPanel_pelvis.setBackground(new java.awt.Color(17, 34, 64));
        jPanel_pelvis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 255, 218), 2, true));

        jLabel_pelvis_puan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_pelvis_puan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pelvis_puan.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\marking.png")); // NOI18N
        jLabel_pelvis_puan.setText("Puanınız : ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\pelvis.png")); // NOI18N
        jLabel11.setText("LEĞEN KEMİĞİ");

        javax.swing.GroupLayout jPanel_pelvisLayout = new javax.swing.GroupLayout(jPanel_pelvis);
        jPanel_pelvis.setLayout(jPanel_pelvisLayout);
        jPanel_pelvisLayout.setHorizontalGroup(
            jPanel_pelvisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pelvisLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(40, 40, 40))
            .addGroup(jPanel_pelvisLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel_pelvis_puan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_pelvisLayout.setVerticalGroup(
            jPanel_pelvisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_pelvisLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel_pelvis_puan)
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel_pelvis, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 270, 220));

        jButton_ileri.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_ileri.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\icons8-forward-50.png")); // NOI18N
        jButton_ileri.setText("İLERİ");
        jButton_ileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ileriActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_ileri, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        jButton_geri.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\turn-left (1).png")); // NOI18N
        jButton_geri.setText("GERİ");
        jButton_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_geriActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_geri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_basMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_basMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel_basMouseEntered

    private void jButton_ileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ileriActionPerformed
        YorumlaFrame yorumEkrani = new YorumlaFrame(tumSonuclar, yanNoktalar, onNoktalar, yanYol, onYol);
        yorumEkrani.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_ileriActionPerformed

    private void jButton_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_geriActionPerformed

        AnteriorAnalizFrame anteriorAnaliz = new AnteriorAnalizFrame(this.yanYol, this.onYol, this.yanNoktalar);
        anteriorAnaliz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_geriActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SonucFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SonucFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SonucFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SonucFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SonucFrame().setVisible(true);
            }
        });
    }
    
    public void analizVeGoster() {
    
    // 1. ADIM: Tekil Analizleri Yap (CalculatePosture kullanarak)
    // Yandan veriler
    AnalizSonucu basTilt = CalculatePosture.basPozisyonuYorumla(yanNoktalar);
    AnalizSonucu servikal = CalculatePosture.servikalLordozYorumla(yanNoktalar);
    AnalizSonucu omuzProt = CalculatePosture.omuzProtraksiyonYorumla(yanNoktalar);
    AnalizSonucu kifoz = CalculatePosture.kifozYorumla(yanNoktalar);
    AnalizSonucu lumbal = CalculatePosture.lumbalLordozYorumla(yanNoktalar);
    AnalizSonucu pelvikTilt = CalculatePosture.pelvikTiltYorumla(yanNoktalar);
    AnalizSonucu dizYan = CalculatePosture.dizPozisyonuYorumla(yanNoktalar);

    // Önden veriler
    AnalizSonucu boyunTilt = CalculatePosture.boyunLateralTiltYorumla(onNoktalar);
    AnalizSonucu omuzSim = CalculatePosture.omuzSimetriYorumla(onNoktalar);
    AnalizSonucu pelvisObliq = CalculatePosture.pelvikObliquityYorumla(onNoktalar);
    AnalizSonucu dizOn = CalculatePosture.dizDizilimiAnteriorYorumla(onNoktalar);
    
    tumSonuclar.addAll(java.util.Arrays.asList(basTilt, servikal, omuzProt, kifoz, lumbal, pelvikTilt, dizYan, boyunTilt, omuzSim, pelvisObliq, dizOn));

    // 2. ADIM: Bölgesel Puanları Hesapla (Senin yazdığın Puanla class'ı kullanarak)
    double boyunPuani = Puanla.boyunPuaniHesapla(basTilt, servikal, boyunTilt);
    double omuzPuani = Puanla.omuzSirtPuaniHesapla(omuzProt, omuzSim);
    double sirtPuani = Puanla.SirtPuaniHesapla(kifoz);
    double belPuani = Puanla.belPuaniHesapla(lumbal);
    double pelvisPuani = Puanla.pelvisPuaniHesapla(pelvikTilt, pelvisObliq);
    double dizPuani = Puanla.altEkstremitePuaniHesapla(dizYan, dizOn);

    // 3. ADIM: Label'lara Yazdır
    // UI üzerindeki jLabel isimlerine göre set et (String.valueOf kullanarak)
    jLabel_bas_puan.setText("Puanınız: " + (int)boyunPuani);
    renklendir(jLabel_bas_puan, boyunPuani);
    jLabel_omuz_puan.setText("Puanınız: " + (int)omuzPuani);
    renklendir(jLabel_omuz_puan, omuzPuani);
    jLabel_sirt_puan.setText("Puanınız: " + ((int)sirtPuani));
    renklendir(jLabel_sirt_puan, sirtPuani);
    jLabel_bel_puan.setText("Puanınız: " +((int)belPuani));
    renklendir(jLabel_bel_puan, belPuani);
    jLabel_pelvis_puan.setText("Puanınız: " +((int)pelvisPuani));
    renklendir(jLabel_pelvis_puan, pelvisPuani);
    jLabel_diz_puan.setText("Puanınız: " +((int)dizPuani));
    renklendir(jLabel_diz_puan, dizPuani);
    
    // Genel Skor (Opsiyonel: Hepsini toplayıp ortalama alabilirsin)
    int genelSkor = (int) Math.round((boyunPuani + omuzPuani + belPuani + pelvisPuani + dizPuani) / 5);
    // jLabel_genel_skor.setText(String.valueOf(genelSkor));
}
    
    private void renklendir(javax.swing.JLabel label, double puan) {
    if (puan >= 85) label.setForeground(new java.awt.Color(100, 255, 218)); // Neon Yeşil
    else if (puan >= 50) label.setForeground(java.awt.Color.ORANGE);
    else label.setForeground(java.awt.Color.RED);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_geri;
    private javax.swing.JButton jButton_ileri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_bas_puan;
    private javax.swing.JLabel jLabel_bel_puan;
    private javax.swing.JLabel jLabel_diz_puan;
    private javax.swing.JLabel jLabel_omuz_puan;
    private javax.swing.JLabel jLabel_pelvis_puan;
    private javax.swing.JLabel jLabel_sirt_puan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_bas;
    private javax.swing.JPanel jPanel_bel;
    private javax.swing.JPanel jPanel_diz;
    private javax.swing.JPanel jPanel_omuz;
    private javax.swing.JPanel jPanel_pelvis;
    private javax.swing.JPanel jPanel_sirt;
    // End of variables declaration//GEN-END:variables
}
