/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package posture_analysis;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class YandanAnalizFrame extends javax.swing.JFrame {
    private String[] referansIsimleri = {
    "1- Tragus", 
    "2- Saç bitim çizgisi", 
    "3- Boyundaki en sivri omur", 
    "4- Omuz tepesi", 
    "5- Sırtın en şişkin noktası", 
    "6- Belin en çukur noktası",
    "7- Kalça yanındaki sert kemik",
    "8- Leğen kemiği önündeki sivri kemik",
    "9- Diz eklem merkezi",
    "10- Ayak bileği eklem merkezi"


    };
    private int mevcutNoktaIndex = 0;
    
    private java.util.List<java.awt.Point> noktalar = new java.util.ArrayList<>();
    
    public YandanAnalizFrame() {
        initComponents();
    }
    public YandanAnalizFrame(String dosyaYolu){
        initComponents();
        try {
        // Dosyanın bilgisayarda var olup olmadığını kontrol ederek açalım
            java.io.File dosya = new java.io.File(dosyaYolu);
        
        if (dosya.exists()) {
            ImageIcon orijinalSimge = new ImageIcon(dosya.getAbsolutePath());
            // Senin istediğin 250x350 boyutuna getiriyoruz
            Image ölçekliResim = orijinalSimge.getImage().getScaledInstance(400, 450, Image.SCALE_SMOOTH);
            jLabel_yandan_foto.setIcon(new ImageIcon(ölçekliResim));
            jLabel_yandan_foto.setText(""); 
            this.revalidate();
            this.repaint();
        } else {
            System.out.println("Analiz için gönderilen dosya yolu bulunamadı: " + dosyaYolu);
            jLabel_yandan_foto.setText("Fotoğraf Yüklenemedi!");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_referans = new javax.swing.JLabel();
        jButton_ileri = new javax.swing.JButton();
        jButton_geri = new javax.swing.JButton();
        jLabel_yandan_foto = new javax.swing.JLabel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                if (noktalar != null) {
                    java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
                    g2d.setColor(java.awt.Color.GREEN);
                    g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                    for (java.awt.Point p : noktalar) {
                        g2d.fillOval(p.x - 5, p.y - 5, 10, 10);
                    }
                }
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 25, 47));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 214, 246));
        jLabel1.setText("YANDAN POSTÜR ANALİZİ İÇİN REFERANS NOKTALARINI İŞARETLEYİN");

        jLabel_referans.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_referans.setForeground(new java.awt.Color(100, 255, 218));
        jLabel_referans.setText("1-Tragus");

        jButton_ileri.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_ileri.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\icons8-forward-50.png")); // NOI18N
        jButton_ileri.setText("İLERİ");
        jButton_ileri.setEnabled(false);
        jButton_ileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ileriActionPerformed(evt);
            }
        });

        jButton_geri.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\turn-left (1).png")); // NOI18N
        jButton_geri.setText("GERİ");
        jButton_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_geriActionPerformed(evt);
            }
        });

        jLabel_yandan_foto.setBackground(new java.awt.Color(0, 102, 102));
        jLabel_yandan_foto.setText("Kullanıcı Yandan Foto");
        jLabel_yandan_foto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_yandan_fotoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_referans)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_geri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ileri)
                        .addGap(139, 139, 139))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jLabel_yandan_foto)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_referans)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel_yandan_foto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                        .addComponent(jButton_geri))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_ileri, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ileriActionPerformed
        try {
            String tamYol = "C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\rehber_ant.png";

            java.io.File dosya = new java.io.File(tamYol);

            if (dosya.exists()) {
                ImageIcon icon = new ImageIcon(dosya.getAbsolutePath());
                // Senin istediğin 600x435 boyutuna getiriyoruz
                Image img = icon.getImage().getScaledInstance(600, 435, Image.SCALE_SMOOTH);

                JLabel lbl = new JLabel(new ImageIcon(img));
                JOptionPane.showMessageDialog(this, lbl, "Analiz Rehberi", JOptionPane.PLAIN_MESSAGE);
                AnteriorAnalizFrame anteriorAnaliz = new AnteriorAnalizFrame(tamYol, noktalar);
                anteriorAnaliz.setVisible(true);
                this.dispose();

            } else {

                System.out.println("Dosya fiziksel olarak yok: " + tamYol);
                JOptionPane.showMessageDialog(this, "Rehber fotoğrafı belirtilen adreste bulunamadı!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton_ileriActionPerformed

    private void jButton_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_geriActionPerformed
        // TODO add your handling code here:
        PhotoFrame fotoFrame = new PhotoFrame();
        fotoFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_geriActionPerformed

    private void jLabel_yandan_fotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_yandan_fotoMouseClicked
        if (mevcutNoktaIndex < 10) {

        java.awt.Point tıklananNokta = evt.getPoint();
        noktalar.add(tıklananNokta);
        
        System.out.println(referansIsimleri[mevcutNoktaIndex] + " kaydedildi: " + tıklananNokta);
        
        jLabel_yandan_foto.repaint();
        mevcutNoktaIndex++;

        if (mevcutNoktaIndex < 10) {
            jLabel_referans.setText(referansIsimleri[mevcutNoktaIndex]);
        } else {
            jLabel_referans.setText("Tüm Noktalar İşaretlendi!");
            jButton_ileri.setEnabled(true); 
        }
    }
    }//GEN-LAST:event_jLabel_yandan_fotoMouseClicked


    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YandanAnalizFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_geri;
    private javax.swing.JButton jButton_ileri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_referans;
    private javax.swing.JLabel jLabel_yandan_foto;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

   
}
