/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package posture_analysis;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class YandanAnalizFrame extends javax.swing.JFrame {
    
    private int zoomX, zoomY;
private boolean showZoom = false;
private final int ZOOM_FACTOR = 2; // 2 kat büyütme
private final int ZOOM_SIZE = 100; // Büyüteç penceresinin boyutu
    
    // Bunu Anterior'a vermek için saklıyoruz
    private String[] referansIsimleri = {
    "1- Tragus", 
    "2- Boyun orta çukuru", 
    "3- Boyundaki en sivri omur", 
    "4- Omuz tepesi", 
    "5- Sırtın en şişkin noktası", 
    "6- Belin en çukur noktası",
    "7- Kalça yanındaki sert kemik",
    "8- Leğen kemiği önündeki sivri kemik",
    "9- Diz eklem merkezi",
    "10- Ayak bileği yanındaki sivri çıkıntı"


    };
    private int mevcutNoktaIndex = 0;
    private String dosyaYolu;
    
    private java.util.List<java.awt.Point> noktalar = new java.util.ArrayList<>();
    private String karsidanProfilYolu;
    public YandanAnalizFrame() {
        initComponents();
    }
    public YandanAnalizFrame(String yanYol, String onYol){
        this.dosyaYolu = yanYol;
        this.karsidanProfilYolu = onYol;
        
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        initComponents();
        
        try {
        // Dosyanın bilgisayarda var olup olmadığını kontrol ederek açalım
            java.io.File dosya = new java.io.File(dosyaYolu);
        
        if (dosya.exists()) {
            ImageIcon orijinalSimge = new ImageIcon(dosya.getAbsolutePath());
            // Senin istediğin 250x350 boyutuna getiriyoruz
            Image ölçekliResim = orijinalSimge.getImage().getScaledInstance(750, 450, Image.SCALE_SMOOTH);
            jLabel_yandan_foto.setIcon(new ImageIcon(ölçekliResim));
            jLabel_yandan_foto.setText(""); 
            this.revalidate();
            this.repaint();
        } else {
            System.out.println("Analiz için gönderilen dosya yolu bulunamadı: " + dosyaYolu);
            jLabel_yandan_foto.setText("Fotoğraf Yüklenemedi!");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_referans = new javax.swing.JLabel();
        jButton_geri = new javax.swing.JButton();
        jButton_ileri = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel_yandan_foto = new javax.swing.JLabel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                if (getIcon() == null) return;

                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
                g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // 1. İşaretlenen noktaları yeşil çiz
                g2d.setColor(java.awt.Color.GREEN);
                if (noktalar != null) {
                    for (java.awt.Point p : noktalar) {
                        g2d.fillOval(p.x - 5, p.y - 5, 10, 10);
                    }
                }

                // 2. Büyüteç (Magnifier) Çizimi
                if (showZoom) {
                    int diameter = 100; // Büyüteç çapı
                    int radius = diameter / 2;

                    // Yuvarlak kesim alanı oluştur
                    g2d.setClip(new java.awt.geom.Ellipse2D.Double(zoomX - radius, zoomY - radius, diameter, diameter));

                    // Resmi 2 kat büyüterek çiz
                    Image img = ((ImageIcon)getIcon()).getImage();
                    g2d.drawImage(img, 
                        zoomX - radius, zoomY - radius, zoomX + radius, zoomY + radius, 
                        zoomX - radius/2, zoomY - radius/2, zoomX + radius/2, zoomY + radius/2, 
                        null);

                    g2d.setClip(null); // Kesimi sıfırla

                    // Beyaz çerçeve ve Kırmızı hedef artısı
                    g2d.setColor(java.awt.Color.WHITE);
                    g2d.setStroke(new java.awt.BasicStroke(2));
                    g2d.drawOval(zoomX - radius, zoomY - radius, diameter, diameter);

                    g2d.setColor(java.awt.Color.RED);
                    g2d.drawLine(zoomX - 10, zoomY, zoomX + 10, zoomY);
                    g2d.drawLine(zoomX, zoomY - 10, zoomX, zoomY + 10);
                }
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 25, 47));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 214, 246));
        jLabel1.setText("YANDAN POSTÜR ANALİZİ İÇİN REFERANS NOKTALARINI İŞARETLEYİN");

        jLabel_referans.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_referans.setForeground(new java.awt.Color(100, 255, 218));
        jLabel_referans.setText("1-Tragus");

        jButton_geri.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\turn-left (1).png")); // NOI18N
        jButton_geri.setText("GERİ");
        jButton_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_geriActionPerformed(evt);
            }
        });

        jButton_ileri.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_ileri.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\icons8-forward-50.png")); // NOI18N
        jButton_ileri.setText("İLERİ");
        jButton_ileri.setEnabled(false);
        jButton_ileri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ileriActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(10, 25, 47));

        jLabel_yandan_foto.setBackground(new java.awt.Color(0, 102, 102));
        jLabel_yandan_foto.setText("Kullanıcı Yandan Foto");
        jLabel_yandan_foto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_yandan_fotoMouseMoved(evt);
            }
        });
        jLabel_yandan_foto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_yandan_fotoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_yandan_fotoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_yandan_fotoMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(jLabel_yandan_foto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel_referans))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_geri)
                                .addGap(543, 543, 543)
                                .addComponent(jButton_ileri)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel_referans)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_geri)
                    .addComponent(jButton_ileri, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ileriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ileriActionPerformed
        try {
        String rehberYolu = "C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\rehber_ant.png";
        java.io.File rehberDosya = new java.io.File(rehberYolu);

        // Rehber görselini pop-up olarak göster
        if (rehberDosya.exists()) {
            ImageIcon icon = new ImageIcon(rehberDosya.getAbsolutePath());
            Image img = icon.getImage().getScaledInstance(600, 435, Image.SCALE_SMOOTH);
            JLabel lbl = new JLabel(new ImageIcon(img));
            JOptionPane.showMessageDialog(this, lbl, "Analiz Rehberi", JOptionPane.PLAIN_MESSAGE);
        }

        AnteriorAnalizFrame anteriorAnaliz = new AnteriorAnalizFrame(this.dosyaYolu, this.karsidanProfilYolu, this.noktalar);
        
        anteriorAnaliz.setVisible(true);
        this.dispose();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Geçiş sırasında hata: " + e.getMessage());
    }
        
        
    }//GEN-LAST:event_jButton_ileriActionPerformed

    private void jButton_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_geriActionPerformed
        // TODO add your handling code here:
        PhotoFrame fotoFrame = new PhotoFrame();
        fotoFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_geriActionPerformed

    private void jLabel_yandan_fotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_yandan_fotoMouseClicked
        if (mevcutNoktaIndex < 10) {

        java.awt.Point tıklananNokta = evt.getPoint();
        noktalar.add(tıklananNokta);
        
        System.out.println(referansIsimleri[mevcutNoktaIndex] + " kaydedildi: " + tıklananNokta);
        
        jLabel_yandan_foto.repaint();
        mevcutNoktaIndex++;

        if (mevcutNoktaIndex < 10) {
            jLabel_referans.setText(referansIsimleri[mevcutNoktaIndex]);
        } else {
            jLabel_referans.setText("Tüm Noktalar İşaretlendi!");
            jButton_ileri.setEnabled(true); 
        }
    }
    }//GEN-LAST:event_jLabel_yandan_fotoMouseClicked

    private void jLabel_yandan_fotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_yandan_fotoMouseEntered
        // TODO add your handling code here:
        showZoom = true;
        jLabel_yandan_foto.repaint();
    }//GEN-LAST:event_jLabel_yandan_fotoMouseEntered

    private void jLabel_yandan_fotoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_yandan_fotoMouseMoved
        // TODO add your handling code here:
        zoomX = evt.getX();
        zoomY = evt.getY();
        showZoom = true; // Tedbiren burada da true yapalım
        jLabel_yandan_foto.repaint();
    }//GEN-LAST:event_jLabel_yandan_fotoMouseMoved

    private void jLabel_yandan_fotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_yandan_fotoMouseExited
        // TODO add your handling code here:
        showZoom = false;
        jLabel_yandan_foto.repaint();
    }//GEN-LAST:event_jLabel_yandan_fotoMouseExited


    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YandanAnalizFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_geri;
    private javax.swing.JButton jButton_ileri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_referans;
    private javax.swing.JLabel jLabel_yandan_foto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   
}
