/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package posture_analysis;

import java.awt.Point;
import java.util.List;

/**
 *
 * @author nhaza
 */
public class YorumlaFrame extends javax.swing.JFrame {
    private List<Point> yanNoktalar; // SonucFrame'den gelen yan noktalar
    private List<Point> onNoktalar;  // SonucFrame'den gelen ön noktalar
    private List<AnalizSonucu> gelenSonuclar;
    String yol;
    
    public YorumlaFrame() {
        initComponents();
    }
    public YorumlaFrame(List<AnalizSonucu> sonuclar,List<Point> yanNoktalar, List<Point> onNoktalar) {
        this.gelenSonuclar = sonuclar;
        this.yanNoktalar = yanNoktalar;
        this.onNoktalar = onNoktalar;
        initComponents();
        yorumlariDoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_diz = new javax.swing.JPanel();
        jLabel_diz_yorum = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel_omuz = new javax.swing.JPanel();
        jLabel_omuz_yorum = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel_bas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_bas_yorum = new javax.swing.JLabel();
        jPanel_sirt = new javax.swing.JPanel();
        jLabel_sirt_yorum = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel_bel = new javax.swing.JPanel();
        jLabel_bel_yorum = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel_pelvis = new javax.swing.JPanel();
        jLabel_pelvis_yorum = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton_geri = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 25, 47));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_diz.setBackground(new java.awt.Color(17, 34, 64));
        jPanel_diz.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 255, 218), 2, true));

        jLabel_diz_yorum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_diz_yorum.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_diz_yorum.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\marking.png")); // NOI18N
        jLabel_diz_yorum.setText("Klinik Yorum : ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\x-ray.png")); // NOI18N
        jLabel12.setText("DİZLER");

        javax.swing.GroupLayout jPanel_dizLayout = new javax.swing.GroupLayout(jPanel_diz);
        jPanel_diz.setLayout(jPanel_dizLayout);
        jPanel_dizLayout.setHorizontalGroup(
            jPanel_dizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_dizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_dizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel_diz_yorum))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel_dizLayout.setVerticalGroup(
            jPanel_dizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_dizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_diz_yorum)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_diz, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 360, 290));

        jPanel_omuz.setBackground(new java.awt.Color(17, 34, 64));
        jPanel_omuz.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 255, 218), 2, true));

        jLabel_omuz_yorum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_omuz_yorum.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_omuz_yorum.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\marking.png")); // NOI18N
        jLabel_omuz_yorum.setText("Klinik Yorum : ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\shoulder.png")); // NOI18N
        jLabel9.setText("OMUZLAR");

        javax.swing.GroupLayout jPanel_omuzLayout = new javax.swing.GroupLayout(jPanel_omuz);
        jPanel_omuz.setLayout(jPanel_omuzLayout);
        jPanel_omuzLayout.setHorizontalGroup(
            jPanel_omuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_omuzLayout.createSequentialGroup()
                .addGroup(jPanel_omuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_omuzLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9))
                    .addGroup(jPanel_omuzLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_omuz_yorum)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel_omuzLayout.setVerticalGroup(
            jPanel_omuzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_omuzLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_omuz_yorum)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_omuz, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 400, 310));

        jPanel_bas.setBackground(new java.awt.Color(17, 34, 64));
        jPanel_bas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 255, 218), 2, true));
        jPanel_bas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_basMouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\kafa.png")); // NOI18N
        jLabel1.setText("BAŞ VE BOYUN");

        jLabel_bas_yorum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_bas_yorum.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_bas_yorum.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\marking.png")); // NOI18N
        jLabel_bas_yorum.setText("Klinik Yorum : ");

        javax.swing.GroupLayout jPanel_basLayout = new javax.swing.GroupLayout(jPanel_bas);
        jPanel_bas.setLayout(jPanel_basLayout);
        jPanel_basLayout.setHorizontalGroup(
            jPanel_basLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_basLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_basLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_bas_yorum))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel_basLayout.setVerticalGroup(
            jPanel_basLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_basLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_bas_yorum)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 310));

        jPanel_sirt.setBackground(new java.awt.Color(17, 34, 64));
        jPanel_sirt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 255, 218), 2, true));

        jLabel_sirt_yorum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_sirt_yorum.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_sirt_yorum.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\marking.png")); // NOI18N
        jLabel_sirt_yorum.setText("Klinik Yorum :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\dromedary.png")); // NOI18N
        jLabel8.setText("SIRT");

        javax.swing.GroupLayout jPanel_sirtLayout = new javax.swing.GroupLayout(jPanel_sirt);
        jPanel_sirt.setLayout(jPanel_sirtLayout);
        jPanel_sirtLayout.setHorizontalGroup(
            jPanel_sirtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sirtLayout.createSequentialGroup()
                .addGroup(jPanel_sirtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_sirtLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8))
                    .addGroup(jPanel_sirtLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_sirt_yorum)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel_sirtLayout.setVerticalGroup(
            jPanel_sirtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_sirtLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_sirt_yorum)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_sirt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 360, 310));

        jPanel_bel.setBackground(new java.awt.Color(17, 34, 64));
        jPanel_bel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 255, 218), 2, true));

        jLabel_bel_yorum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_bel_yorum.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_bel_yorum.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\marking.png")); // NOI18N
        jLabel_bel_yorum.setText("Klinik Yorum  :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\back-pain.png")); // NOI18N
        jLabel10.setText("BEL");

        javax.swing.GroupLayout jPanel_belLayout = new javax.swing.GroupLayout(jPanel_bel);
        jPanel_bel.setLayout(jPanel_belLayout);
        jPanel_belLayout.setHorizontalGroup(
            jPanel_belLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_belLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_belLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel_bel_yorum))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel_belLayout.setVerticalGroup(
            jPanel_belLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_belLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_bel_yorum)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_bel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 380, 290));

        jPanel_pelvis.setBackground(new java.awt.Color(17, 34, 64));
        jPanel_pelvis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 255, 218), 2, true));

        jLabel_pelvis_yorum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_pelvis_yorum.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pelvis_yorum.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\marking.png")); // NOI18N
        jLabel_pelvis_yorum.setText("Klinik Yorum : ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\pelvis.png")); // NOI18N
        jLabel11.setText("LEĞEN KEMİĞİ");

        javax.swing.GroupLayout jPanel_pelvisLayout = new javax.swing.GroupLayout(jPanel_pelvis);
        jPanel_pelvis.setLayout(jPanel_pelvisLayout);
        jPanel_pelvisLayout.setHorizontalGroup(
            jPanel_pelvisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pelvisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_pelvisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel_pelvis_yorum))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel_pelvisLayout.setVerticalGroup(
            jPanel_pelvisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_pelvisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_pelvis_yorum)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_pelvis, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 400, 290));

        jButton_geri.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\turn-left (1).png")); // NOI18N
        jButton_geri.setText("GERİ");
        jButton_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_geriActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_geri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nhaza\\OneDrive\\Documents\\NetBeansProjects\\Postur_Analizi\\src\\main\\java\\posture_analysis\\icons\\bookmark (1).png")); // NOI18N
        jButton1.setText("KAYDET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 640, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1173, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_basMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_basMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel_basMouseEntered

    private void jButton_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_geriActionPerformed
        SonucFrame sonucEkrani = new SonucFrame(this.yanNoktalar, this.onNoktalar,yol);
        sonucEkrani.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_geriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YorumlaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YorumlaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YorumlaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YorumlaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YorumlaFrame().setVisible(true);
            }
        });
    }
    
    public void yorumlariDoldur() {
    try {
        // 1. ADIM: Tekil Analizleri Yap (CalculatePosture sınıfından AnalizSonucu nesnelerini al)
        AnalizSonucu basSonuc = CalculatePosture.basPozisyonuYorumla(yanNoktalar);
        AnalizSonucu servikalSonuc = CalculatePosture.servikalLordozYorumla(yanNoktalar);
        AnalizSonucu omuzProtSonuc = CalculatePosture.omuzProtraksiyonYorumla(yanNoktalar);
        AnalizSonucu kifozSonuc = CalculatePosture.kifozYorumla(yanNoktalar);
        AnalizSonucu lumbalSonuc = CalculatePosture.lumbalLordozYorumla(yanNoktalar);
        AnalizSonucu pelvikTiltSonuc = CalculatePosture.pelvikTiltYorumla(yanNoktalar);
        AnalizSonucu dizYanSonuc = CalculatePosture.dizPozisyonuYorumla(yanNoktalar);

        AnalizSonucu boyunTiltSonuc = CalculatePosture.boyunLateralTiltYorumla(onNoktalar);
        AnalizSonucu omuzSimSonuc = CalculatePosture.omuzSimetriYorumla(onNoktalar);
        AnalizSonucu pelvisObliqSonuc = CalculatePosture.pelvikObliquityYorumla(onNoktalar);
        AnalizSonucu dizOnSonuc = CalculatePosture.dizDizilimiAnteriorYorumla(onNoktalar);
        
        jLabel_bas_yorum.setText("<html>" + basSonuc.yorum + "<br>" + boyunTiltSonuc.yorum + "</html>");
        jLabel_omuz_yorum.setText("<html>" + omuzProtSonuc.yorum + "<br>" + omuzSimSonuc.yorum + "</html>");
        jLabel_sirt_yorum.setText("<html>" + kifozSonuc.yorum + "</html>");
        jLabel_bel_yorum.setText("<html>" + lumbalSonuc.yorum + "</html>");
        jLabel_pelvis_yorum.setText("<html>" + pelvikTiltSonuc.yorum + "<br>" + pelvisObliqSonuc.yorum + "</html>");
        jLabel_diz_yorum.setText("<html>" + dizYanSonuc.yorum + "<br>" + dizOnSonuc.yorum + "</html>");
        } catch (Exception e) {
        System.err.println("Analiz hatası: " + e.getMessage());
    }
}
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_geri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_bas_yorum;
    private javax.swing.JLabel jLabel_bel_yorum;
    private javax.swing.JLabel jLabel_diz_yorum;
    private javax.swing.JLabel jLabel_omuz_yorum;
    private javax.swing.JLabel jLabel_pelvis_yorum;
    private javax.swing.JLabel jLabel_sirt_yorum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_bas;
    private javax.swing.JPanel jPanel_bel;
    private javax.swing.JPanel jPanel_diz;
    private javax.swing.JPanel jPanel_omuz;
    private javax.swing.JPanel jPanel_pelvis;
    private javax.swing.JPanel jPanel_sirt;
    // End of variables declaration//GEN-END:variables
}
